package kt.module.module_base.data.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import kt.module.module_base.data.db.table.ChildEntity;
import kt.module.module_base.data.db.table.ObjectEntity;
import kt.module.module_base.data.db.table.RvData;

import kt.module.module_base.data.db.dao.ChildEntityDao;
import kt.module.module_base.data.db.dao.ObjectEntityDao;
import kt.module.module_base.data.db.dao.RvDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig childEntityDaoConfig;
    private final DaoConfig objectEntityDaoConfig;
    private final DaoConfig rvDataDaoConfig;

    private final ChildEntityDao childEntityDao;
    private final ObjectEntityDao objectEntityDao;
    private final RvDataDao rvDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        childEntityDaoConfig = daoConfigMap.get(ChildEntityDao.class).clone();
        childEntityDaoConfig.initIdentityScope(type);

        objectEntityDaoConfig = daoConfigMap.get(ObjectEntityDao.class).clone();
        objectEntityDaoConfig.initIdentityScope(type);

        rvDataDaoConfig = daoConfigMap.get(RvDataDao.class).clone();
        rvDataDaoConfig.initIdentityScope(type);

        childEntityDao = new ChildEntityDao(childEntityDaoConfig, this);
        objectEntityDao = new ObjectEntityDao(objectEntityDaoConfig, this);
        rvDataDao = new RvDataDao(rvDataDaoConfig, this);

        registerDao(ChildEntity.class, childEntityDao);
        registerDao(ObjectEntity.class, objectEntityDao);
        registerDao(RvData.class, rvDataDao);
    }
    
    public void clear() {
        childEntityDaoConfig.clearIdentityScope();
        objectEntityDaoConfig.clearIdentityScope();
        rvDataDaoConfig.clearIdentityScope();
    }

    public ChildEntityDao getChildEntityDao() {
        return childEntityDao;
    }

    public ObjectEntityDao getObjectEntityDao() {
        return objectEntityDao;
    }

    public RvDataDao getRvDataDao() {
        return rvDataDao;
    }

}
